package com.legacy.structure_gel.structures.jigsaw;

import java.util.List;

import com.mojang.datafixers.util.Pair;

import net.minecraft.util.ResourceLocation;
import net.minecraft.world.gen.feature.jigsaw.JigsawManager;
import net.minecraft.world.gen.feature.jigsaw.JigsawPattern;
import net.minecraft.world.gen.feature.jigsaw.JigsawPiece;

/**
 * Assists in the registry process for Jigsaw structures to shorten names and
 * give shorter methods. This is used along with {@link JigsawPoolBuilder}
 * 
 * @author David
 *
 */
public class JigsawRegistryHelper
{
	private String modid;
	private String prefix;

	public JigsawRegistryHelper(String modid)
	{
		this(modid, "");
	}

	/**
	 * 
	 * @param modid : The mod. Duh.
	 * @param prefix : Placed between modid and the name provided in the resource
	 *            location generated by the JigsawPoolBuilder. Leave this field
	 *            blank if you don't want to worry about it.
	 */
	public JigsawRegistryHelper(String modid, String prefix)
	{
		this.modid = modid;
		this.prefix = prefix;
	}

	public void setModID(String modid)
	{
		this.modid = modid;
	}

	public void setPrefix(String prefix)
	{
		this.prefix = prefix;
	}

	/**
	 * Quick way to get a {@link JigsawPoolBuilder} from the registry instance. You
	 * could also do this in the pool builder.
	 * 
	 * @return {@link JigsawPoolBuilder}
	 */
	public JigsawPoolBuilder builder()
	{
		return new JigsawPoolBuilder(this);
	}

	/**
	 * Registers a jigsaw pool in JigsawManager.REGISTRY. For most simple cases, you
	 * can use {@link #register(String, List)} or
	 * {@link #register(ResourceLocation, List)}
	 * 
	 * @param poolName : The name of the pool. Other jigsaw blocks will ask for
	 *            this, so make sure it matches. Uses {@link #locatePiece(String)}
	 *            with the prefix and modid included. Use a ResourceLocation instead
	 *            to set it yourself.
	 * @param defaultPool : The default pool if it fails I think. Not sure. Uses
	 *            JigsawRegistryHelper.prefix. "minecraft:empty" by default. TODO
	 *            Needs better documentation.
	 * @param pool : The structurs that this pool can generate. Use a
	 *            {@link JigsawPoolBuilder} from {@link #builder()} for simplicity.
	 * @param placement : How the structure will place. Rigid by default.
	 */
	public void register(String poolName, String defaultPool, List<Pair<JigsawPiece, Integer>> pool, JigsawPattern.PlacementBehaviour placement)
	{
		JigsawManager.REGISTRY.register(new JigsawPattern(locatePiece(poolName), locatePiece(defaultPool), pool, placement));
	}

	public void register(String poolName, String defaultPool, List<Pair<JigsawPiece, Integer>> pool)
	{
		register(poolName, defaultPool, pool, JigsawPattern.PlacementBehaviour.RIGID);
	}

	public void register(String poolName, List<Pair<JigsawPiece, Integer>> pool, JigsawPattern.PlacementBehaviour placement)
	{
		register(locatePiece(poolName), new ResourceLocation("empty"), pool, placement);
	}

	/**
	 * Registers a jigsaw pool in JigsawManager.REGISTRY.
	 * 
	 * @param poolName : the name of the pool. Other jigsaw blocks will ask for
	 *            this, so make sure it matches. Uses {@link #locatePiece(String)}
	 *            with the prefix and modid included. Use a ResourceLocation instead
	 *            to set it yourself.
	 * @param pool : The structurs that this pool can generate. Use a
	 *            {@link JigsawPoolBuilder} from {@link #builder()} for simplicity.
	 */
	public void register(String poolName, List<Pair<JigsawPiece, Integer>> pool)
	{
		register(poolName, pool, JigsawPattern.PlacementBehaviour.RIGID);
	}

	public void register(ResourceLocation poolName, ResourceLocation defaultPool, List<Pair<JigsawPiece, Integer>> pool, JigsawPattern.PlacementBehaviour placement)
	{
		JigsawManager.REGISTRY.register(new JigsawPattern(poolName, defaultPool, pool, placement));
	}

	public void register(ResourceLocation poolName, ResourceLocation defaultPool, List<Pair<JigsawPiece, Integer>> pool)
	{
		register(poolName, defaultPool, pool, JigsawPattern.PlacementBehaviour.RIGID);
	}

	public void register(ResourceLocation poolName, List<Pair<JigsawPiece, Integer>> pool, JigsawPattern.PlacementBehaviour placement)
	{
		register(poolName, new ResourceLocation("empty"), pool, placement);
	}

	/**
	 * Registers a jigsaw pool in JigsawManager.REGISTRY.
	 * 
	 * @param poolName : the name of the pool. Other jigsaw blocks will ask for
	 *            this, so make sure it matches.
	 * @param pool : The structurs that this pool can generate. Use a
	 *            {@link JigsawPoolBuilder} from {@link #builder()} for simplicity.
	 */
	public void register(ResourceLocation poolName, List<Pair<JigsawPiece, Integer>> pool)
	{
		register(poolName, pool, JigsawPattern.PlacementBehaviour.RIGID);
	}

	/**
	 * Gets a ResourceLocation for the key input using the modid and prefix.
	 * modid:prefix+key
	 * 
	 * @param key
	 * @return {@link ResourceLocation}
	 */
	public ResourceLocation locatePiece(String key)
	{
		return new ResourceLocation(this.modid, this.prefix + key);
	}
}