modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://gitlab.com/groups/modding-legacy/-/issues"
[[mods]]
modId="structure_gel"
version="${file.jarVersion}"
displayName="Structure Gel API"
displayURL="https://moddinglegacy.com/"
logoFile="banner.png"
credits=""
authors="Silver_David"
description='''An API mod to simplify structure generation on the developers'''
[[dependencies.structure_gel]]
    modId="forge"
    mandatory=true
    versionRange="[31.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.structure_gel]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"