modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://gitlab.com/modding-legacy/structure-gel-api/-/issues"
license="https://www.gnu.org/licenses/gpl-3.0.en.html"
[[mods]]
	modId="structure_gel"
	version="${file.jarVersion}"
	displayName="Structure Gel API"
	displayURL="https://moddinglegacy.com/"
	logoFile="logo.png"
	authors="Silver_David, KingPhygieBoo, Jonathing"
	description='''An API mod to improve the developer side of structure gen'''
    license="https://www.gnu.org/licenses/gpl-3.0.en.html"
[[dependencies.structure_gel]]
    modId="forge"
    mandatory=true
    versionRange="[35.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.structure_gel]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"