modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://gitlab.com/groups/modding-legacy/-/issues"
[[mods]]
	modId="structure_gel"
	version="${file.jarVersion}"
	displayName="Structure Gel API"
	displayURL="https://moddinglegacy.com/"
	logoFile="logo.png"
	credits="KingPhygieBoo"
	authors="Silver_David"
	description='''An API mod to improve the developer side of structure gen'''
[[dependencies.structure_gel]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.97,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.structure_gel]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"