modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://gitlab.com/modding-legacy/structure-gel-api/-/issues"
license="https://www.gnu.org/licenses/gpl-3.0.en.html"
[[mods]]
	modId="structure_gel"
	version="${file.jarVersion}"
	displayName="Structure Gel API"
	displayURL="https://moddinglegacy.com/"
	logoFile="logo.png"
	credits=""
	authors="Silver_David, KingPhygieBoo"
	description='''An API mod to improve the developer side of structure gen'''
    license="https://www.gnu.org/licenses/gpl-3.0.en.html"
[[dependencies.structure_gel]]
    modId="forge"
    mandatory=true
    versionRange="[34.0.7,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.structure_gel]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"